### ISSUE TITLE
A device may only appear in the once in the data source list (Mountpoints)

### ISSUE THREAD

**Issue by mentalinc** [BlueBlock/Elucidate#2]
I get this error with only the first snapshot sourced listed with the error "A device may only appear in the once in the data source list"

I use C:\DiskMount\ to mount all my drives instead of driver letters..
e.g.
C:\DiskMount\D1
C:\DiskMount\D2
C:\DiskMount\D...

Seems the check is a bit too basic....

As a result I'm not able to exit the settings menu at all...
Maybe need to add an exit and ignore invlaid config option as "end task" doesn't seem like the best option.

**Comment by BlueBlock** [comment]
You're data disk config section looks something like this?

data d1 C:\DiskMount\D1
data d2 C:\DiskMount\D2

**Comment by szemenyeigy** [comment]
Same here, I have my disks set up like this:
data d1 C:\mnt\D1\
data d2 C:\mnt\D2\
data d3 C:\mnt\D3\
data d4 C:\mnt\D4\
etc...

**Comment by BlueBlock** [comment]
Are the D1 , D2 etc folders or references to drives?

**Comment by szemenyeigy** [comment]
They are mounted to an empty NTFS folder using the built-in disk manager. 
https://docs.microsoft.com/en-us/windows-server/storage/disk-management/assign-a-mount-point-folder-path-to-a-drive
![image](https://user-images.githubusercontent.com/4790908/44362511-81e96480-a4c1-11e8-810c-6bdfd0e3b5f1.png)
This way you don't have to assign drive letters to each drive. It's a really useful feature when you have many disks.

**Comment by BlueBlock** [comment]
Thanks.. I'll investigate this.

**Comment by BlueBlock** [comment]
I do see the primary issue. I'm also enhancing the drive list to include folder mounted drives.

![image](https://user-images.githubusercontent.com/476010/44378012-46ed2e00-a4cd-11e8-9c64-84571b9a3133.png)
